### PR TITLE
Replace OpenAI-Whisper with Faster-Whisper

### PR DESCRIPTION
**Pull request by faker2048**
This PR aims to enhance the efficiency by replacing OpenAI-Whisper with[ Faster-Whisper](https://github.com/guillaumekln/faster-whisper). 

### faster-whisper can provide
-  **4x** speed improvement in **model inference**
-  reducing **GPU memory usage** by approximately **50%** without compromising on the accuracy.

### Here is what this Pull Request includes

- Replacing OpenAI-Whisper with Faster-Whisper: The replacement of OpenAI-Whisper with Faster-Whisper is aimed at improving the performance of the model without compromising its accuracy. 

- Adding the `torch` to requirements.txt: This addition is intended to support CUDA and provide console output for `torch.cuda.is_available` to inform the user whether CUDA is enabled or not.

### Tests performed

- Linux: The speech_to_text functionality worked as expected and GPU support was intact.

- Under Docker: Everything functioned normally. However, due to the settings of the Dockerfile image, it did not support GPU usage and hence, CPU mode was enabled.

Your review and feedback on this PR would be greatly appreciated.

### CODE REVIEW

**Comment by pycui** [comment]
Get an error in the whisper transcribing when testing this PR:
```
2023-08-07 14:18:30,204 - transcribe - whisper.py - INFO - Transcribing audio...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 292, in app
    await dependant.call(**values)
  File "/Users/bcstyle/Documents/copilot/GPTinterviewer/realtime_ai_character/websocket_routes.py", line 93, in websocket_endpoint
    await asyncio.gather(main_task)
  File "/Users/bcstyle/Documents/copilot/GPTinterviewer/realtime_ai_character/websocket_routes.py", line 266, in handle_receive
    transcript: str = (await asyncio.to_thread(speech_to_text.transcribe,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bcstyle/.pyenv/versions/3.11.3/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bcstyle/.pyenv/versions/3.11.3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bcstyle/Documents/copilot/GPTinterviewer/realtime_ai_character/audio/speech_to_text/whisper.py", line 63, in transcribe
    return self._transcribe(audio, prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bcstyle/Documents/copilot/GPTinterviewer/realtime_ai_character/audio/speech_to_text/whisper.py", line 69, in _transcribe
    segs, _ = self.model.transcribe(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 241, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bcstyle/Documents/copilot/.venv/lib/python3.11/site-packages/faster_whisper/audio.py", line 45, in decode_audio
    with av.open(input_file, metadata_errors="ignore") as container:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av/container/core.pyx", line 401, in av.container.core.open
  File "av/container/core.pyx", line 246, in av.container.core.Container.__cinit__
  File "av/container/pyio.pyx", line 44, in av.container.pyio.PyIOFile.__cinit__
ValueError: File object has no read() method, or readable() returned False.
```

**Comment by pycui** [comment]
same issue happens with docker.

It seems to me the issues because the Faster Whisper lib accepts a different format (BytesIO) instead of AudioData. I add a commit to handle these two conditions (local whisper vs remote whisper) in your PR. how me know if you concerns. Thanks!

**Comment by faker2048** [comment]
Thanks for your review and testing.
I have noticed the change from `segment["text"]` to `segment.text`, and it appears that the code didn't run to this line. As a result, I may have conducted some erroneous tests, possibly due to using the remote whisper. I would like to sincerely apologize for this oversight. 
Anyway, I'm a bit concerned, is it able to run in both CUDA and non-CUDA modes?

**Comment by pycui** [comment]
I haven't got chance to test it on CUDA, but CPU definitely works fine. Feel free to suggest future change on this by open a new PR!

**Comment by jfaraklit** [comment]
@faker2048  @HongSiu  @pycui  I see this error when building docker image. about torch
image

**Pull request merged**
