### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by gladiopeace**
pypdf is required to ingest pdfs character dataset

### CODE REVIEW

**Comment by pycui** [comment]
Thanks! This sounds a good idea. Is there any change needed, or this one-liner is enough to work?

**Comment by gladiopeace** [comment]
> Thanks! This sounds a good idea. Is there any change needed, or this one-liner is enough to work?

added two more dependencies to hangle epub format
EbookLib
html2text

**Comment by pycui** [comment]
Thanks! Can you sort in alphabetically?

**Comment by pycui** [comment]
sorted and merged main.

**Pull request merged**
